install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("vegan")
install.packages("devtools")
devtools::install_version("rlang", " 1.0.0")
install.packages("BiocManager")
BiocManager::install(c("phyloseq", "microbiome", "ComplexHeatmap"), update = FALSE)
devtools::install_github("david-barnett/microViz", upgrade=FALSE)
